version: '3'

# docker-compose -f docker-compose.yml build
# docker-compose -f docker-compose.yml up 
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flaskdb
    ports:
      - "5432:5432"
    networks:
      - default 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5


  app:
    build: ./app
    container_name: flsite
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    
    networks:
      - default 
    depends_on:
      db:
        condition: service_healthy

networks:
  default: